vsp=0;hsp=0;grv=0.3;immune=false;
image_speed=0;
depth=depth+10;
rW=room_width;
tilemap = layer_tilemap_get_id("Collision");
tilemap2 = layer_tilemap_get_id("Platform");
attacking=false;dir=noone;
curvePosition = 0;
curveSpeed = 0.005;
distance = 0;
move=false;
jump = false;
cKordaja=0.4;
elud=25;
maxelud=25;
blocker=0;
atkDete=500;
jumps=0;
platformblock=true;
colblock=false;