hsp = 0;
vsp = 0;
floatlock=false;
wet=false;
grv=0.3;
elud=10;
wet=false;
tilemap = layer_tilemap_get_id("Collision");
tilemap2 = layer_tilemap_get_id("Platform");
tilemap3 = layer_tilemap_get_id("CollisionSmall");
walksp=2;
landed=false;
chase=false;
image_speed=0;
image_index=5;
jumping=false;
blocker=false;
canatk=true;
anger=0;
stucker=0;
eating=false;
treatment=false;
who=noone;
image_xscale=-0.7;
image_yscale=0.7;
immune=false;
shot=0;
allowlandsn=false;
allowdrop=false;
foreverchase=true;
jump=false;
alarm[0]=40; // jump or fall
alarm[2]=60;
havelanded=false;
var epth=layer_get_depth("Characters");
depth=epth-14;
yy=self.y-100;


